Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace mvc_energy_plants.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CustomerName { get; set; }
        public string Country { get; set; }
        public double PowerGeneration { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }

        [Display(Name = "Operation Date")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }


    }
}

Controllers/ProjectStopLogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_energy_plants.Models;

namespace mvc_energy_plants.Controllers
{
    public class ProjectStopLogsController : Controller
    {
        private readonly energy_plantsContext _context;

        public ProjectStopLogsController(energy_plantsContext context)
        {
            _context = context;
        }

        // GET: ProjectStopLogs
        public async Task<IActionResult> Index()
        {
            return _context.ProjectStopLog != null ?
                        View(await _context.ProjectStopLog.ToListAsync()) :
                        Problem("Entity set 'energy_plantsContext.ProjectStopLog'  is null.");
        }

        // GET: ProjectStopLogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProjectStopLog == null)
            {
                return NotFound();
            }

            var projectStopLog = await _context.ProjectStopLog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectStopLog == null)
            {
                return NotFound();
            }

            return View(projectStopLog);
        }

        // GET: ProjectStopLogs/Create
        public IActionResult Create(int projectId)
        {
            this.ViewData["projectId"] = projectId;
            return View();
        }

        // POST: ProjectStopLogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProjectId,StopDate,Classification,Cause,Action")] ProjectStopLog projectStopLog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projectStopLog);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Projects", new { id = projectStopLog.ProjectId });
            }
            return View(projectStopLog);
        }

        // GET: ProjectStopLogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProjectStopLog == null)
            {
                return NotFound();
            }

            var projectStopLog = await _context.ProjectStopLog.FindAsync(id);
            if (projectStopLog == null)
            {
                return NotFound();
            }
            return View(projectStopLog);
        }

        // POST: ProjectStopLogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProjectId,StopDate,Classification,Cause,Action")] ProjectStopLog projectStopLog)
        {
            if (id != projectStopLog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectStopLog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectStopLogExists(projectStopLog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Projects", new { id = projectStopLog.ProjectId });
            }
            return View(projectStopLog);
        }

        // GET: ProjectStopLogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProjectStopLog == null)
            {
                return NotFound();
            }

            var projectStopLog = await _context.ProjectStopLog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectStopLog == null)
            {
                return NotFound();
            }

            return View(projectStopLog);
        }

        // POST: ProjectStopLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProjectStopLog == null)
            {
                return Problem("Entity set 'energy_plantsContext.ProjectStopLog'  is null.");
            }
            var projectStopLog = await _context.ProjectStopLog.FindAsync(id);
            if (projectStopLog != null)
            {
                _context.ProjectStopLog.Remove(projectStopLog);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Projects", new { id = projectStopLog.ProjectId });
        }

        private bool ProjectStopLogExists(int id)
        {
            return (_context.ProjectStopLog?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using mvc_energy_plants.Models;
using Project = mvc_energy_plants.Models.Project;

namespace mvc_energy_plants.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly energy_plantsContext _context;

        public ProjectsController(energy_plantsContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Project == null)
            {
                return Problem("Entity is null.");
            }


            var projects = _context.Project.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                projects = projects.Where(x => x.Name!.Contains(searchString));
            }


            ViewBag.ChartValue = projects
                .GroupBy(x => x.StartDate)
                .Select(std => new { year = std.Key.Year, count = std.Count() })
                .ToList();

            return View(await projects.ToListAsync());

        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            var projectLogs = _context.ProjectStopLog.Where(m => m.ProjectId == id).ToList();


            var tuple = new Tuple<Project, List<ProjectStopLog>>(project, projectLogs);
            return View(tuple);
        }



        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Code,CustomerName,Country,PowerGeneration,Longitude,Latitude,StartDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Code,CustomerName,Country,PowerGeneration,Longitude,Latitude,StartDate")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Projects", new { id = project.Id });
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Project == null)
            {
                return Problem("Entity set 'energy_plantsContext.Project'  is null.");
            }
            var project = await _context.Project.FindAsync(id);
            if (project != null)
            {
                _context.Project.Remove(project);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return (_context.Project?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Projects/Create.cshtml
@model mvc_energy_plants.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h1>Create Project</h1>
<div>
    <a class="btn btn-primary" asp-action="Index"><i class="material-icons">arrow_back</i></a>
</div>

<hr />
<div class="row">

    <form asp-action="Create" id="formCreate">
        <div class="row">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Code" class="control-label"></label>
                    <input asp-for="Code" class="form-control" />
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerName" class="control-label"></label>
                    <input asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Country" class="control-label"></label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="PowerGeneration" class="control-label"></label>
                    <input asp-for="PowerGeneration" class="form-control" />
                    <span asp-validation-for="PowerGeneration" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Longitude" class="control-label"></label>
                    <input asp-for="Longitude" class="form-control" />
                    <span asp-validation-for="Longitude" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Latitude" class="control-label"></label>
                    <input asp-for="Latitude" class="form-control" />
                    <span asp-validation-for="Latitude" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group mt-3">
                <a href="#" onclick="formSubmit('formCreate')" value="Create" class="btn btn-primary" /><i class="material-icons">save</i> </a>
            </div>
        </div>
    </form>
</div>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Projects/Delete.cshtml
@model mvc_energy_plants.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PowerGeneration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PowerGeneration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />

        <a class="btn btn-secondary" asp-action="Index"><i class="material-icons">arrow_back</i></a>|
        <input type="submit" value="Delete" class="btn btn-danger" />

    </form>
</div>

Views/Projects/Details.cshtml
@using mvc_energy_plants.Models;

@model Tuple<Project ,List<ProjectStopLog>>

@{
    ViewData["Title"] = "Details";
}


<div>
    <h3>Details Project</h3>
    <a class="btn btn-primary" asp-action="Index"><i class="material-icons">arrow_back</i></a>
    <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model?.Item1.Id"><i class="material-icons">mode_edit</i></a>
</div>

<div>

    <hr />
    <div class="row">
        <div class="col">
            <dl class="row">

                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.Name)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.Name)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.Code)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.Code)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.CustomerName)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.CustomerName)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.Country)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.Country)
                </dd>

            </dl>
        </div>
        <div class="col">
            <dl class="row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.PowerGeneration)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.PowerGeneration)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.Longitude)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.Longitude)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.Latitude)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.Latitude)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Item1.StartDate)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Item1.StartDate)
                </dd>
            </dl>
        </div>
    </div>
</div>


<hr />

<a asp-controller="ProjectStopLogs" asp-action="Create" asp-route-projectId="@Model?.Item1.Id"><i class="material-icons" style="font-size:36px">note_add</i></a>

@if (Model?.Item2 != null)
{
    <div>
        <table id="tble" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Item2.FirstOrDefault().StopDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Item2.FirstOrDefault().Classification)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Item2.FirstOrDefault().Cause)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Item2.FirstOrDefault().Action)
                    </th>
                    <th>

                    </th>

            </thead>
            <tbody>
                @foreach (var item in Model.Item2)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.StopDate)</td>
                        <td>@Html.DisplayFor(modelItem => item.Classification)</td>
                        <td>@Html.DisplayFor(modelItem => item.Cause)</td>
                        <td>@Html.DisplayFor(modelItem => item.Action)</td>

                        <td>


                            <a asp-controller="ProjectStopLogs" asp-action="Edit" asp-route-id="@item.Id"><i style="font-size:1.2em" class="material-icons">mode_edit</i></a>
                            <a asp-controller="ProjectStopLogs" asp-action="Details" asp-route-id="@item.Id"><i style="color:green; font-size:1.2em" class="material-icons">info</i></a>
                            <a asp-controller="ProjectStopLogs" asp-action="Delete" asp-route-id="@item.Id"><i style="color:red; font-size:1.2em" class="material-icons">delete</i></a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>


}
else
{
    <div>No data</div>
}




@section Scripts{
    <script>
        $("table#tble").Grid();
    </script>
}

Views/Projects/Edit.cshtml
@model mvc_energy_plants.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Project</h1>


<div>
    <a class="btn btn-primary"
       asp-controller="Projects"
       asp-action="Details"
       asp-route-id="@Model.Id"><i class="material-icons">arrow_back</i></a>
</div>
<hr />
<div class="row">

    <form asp-action="Edit" id="formEdit">
        <div class="row">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Code" class="control-label"></label>
                    <input asp-for="Code" class="form-control" />
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerName" class="control-label"></label>
                    <input asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Country" class="control-label"></label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="PowerGeneration" class="control-label"></label>
                    <input asp-for="PowerGeneration" class="form-control" />
                    <span asp-validation-for="PowerGeneration" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Longitude" class="control-label"></label>
                    <input asp-for="Longitude" class="form-control" />
                    <span asp-validation-for="Longitude" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Latitude" class="control-label"></label>
                    <input asp-for="Latitude" class="form-control" />
                    <span asp-validation-for="Latitude" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>

            </div>

            <div class="form-group mt-3">
                <a href="#" onclick="formSubmit('formEdit')" value="Save" class="btn btn-primary"><i class="material-icons">save</i> </a>
            </div>
        </div>
    </form>

</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Projects/Index.cshtml
@model IEnumerable<mvc_energy_plants.Models.Project>
@using System.Web.Helpers

@{
    ViewData["Title"] = "Index";
}



<table id="indexTable" class="table table-bordered table-hover">



    <a asp-action="Create"><i class="material-icons" style="font-size:36px">note_add</i></a>

    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PowerGeneration)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PowerGeneration)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>


                    @*<a asp-action="Edit" asp-route-id="@item.Id"><i style="font-size:1.2em" class="material-icons">mode_edit</i></a>*@
                    <a asp-action="Details" asp-route-id="@item.Id"><i style="color:green; font-size:1.2em" class="material-icons">info</i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id"><i style="color:red; font-size:1.2em" class="material-icons">delete</i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <canvas id="myChart" height="60"></canvas>
</div>


@section Scripts {
    <script>
        const gg = $("table#indexTable").Grid({
            search: true,
            sort: true,
            resizable: true,
            pagination: {
                limit: 5,
                summary: false
            }
        });

        const ctx = document.getElementById('myChart');
        var data1 = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.ChartValue))')
        console.log(data1)
        data1.forEach(x => console.log(x))





        new Chart(ctx, {
            type: 'bar',

            data: {
                labels: data1.map(x => x.year),
                datasets: [{
                    label: 'Operation Year',
                    data: data1.map(x => x.count),
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
}